### ISSUE TITLE
Add template based magnitude-amplitude regression from seismatch and adapt for RT use.

### ISSUE THREAD

**Issue by ramasuri-CH** [damb/scdetect#34]
**References**:
- [seismatch](https://gitlab.seismo.ethz.ch/microEQ/TM) sources
- https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JB017468

**Comment by damb** [comment]
**Roadmap** (after the discussion with @ramasuri-CH):
- The scope of `scdetect` module will be limited to:
  + generate detections and declare origins (currently detection is performed based on cross-correlation)
  + compute and declare amplitudes.

  This is similar to the approach chosen by [scautopick](https://www.seiscomp.de/doc/apps/scautopick.html).
- Both the `scdetect` origins and the `scdetect` amplitudes are going to be consumed by a second module i.e. `scdetect-mag` which is going to compute:
  + Station magnitudes (based on a *template-family magnitude-amplitude regression* approach)
  + Network magnitudes

- Magnitudes and origins are going to be associated by [scevent](https://www.seiscomp.de/doc/apps/scevent.html).

This way the `scdetect` configuration is not going to be spoiled with configuration required for calculating magnitudes. Hence, magnitude related configuration is provided by the dedicated `scdetect-mag` configuration.

**Comment by luca-s** [comment]
This sounds very neat.

**Comment by damb** [comment]
With #48 `scdetect` implements amplitude calculation.

Now, thinking about the calculation of magnitudes, I'm not sure whether a dedicated module is the right approach. Currently, I rather tend to implement the *amplitude-magnitude regression* within `scdetect`:

- Both the declared origin and the calculated amplitudes are already available. No need to fetch and buffer this data within e.g. a `DataModel::PublicObjectTimeSpanBuffer`.
- Implementing a dedicated module would require both to parse the template configuration (e.g. `templates.json`) and to load event metadata, again. E.g. the very first magnitude of a template family is the magnitude of the template itself (in case of a single sensor-location detector configuration).

The question is still how to provide the magnitude related configuration without spoiling the `templates.json` template configuration file.
