### ISSUE TITLE
Alternative magnitude implementation: amplitude ratio between template and detected event

### ISSUE THREAD

**Issue by damb** [damb/scdetect#70]
### Discussed in https://github.com/damb/scdetect/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **mmesim** November  4, 2021</sup>
Ideas for magnitude calculation based on what is already available and used in the literature (etc). 
- **Amplitude ratio between template and detected event**
e.g  https://www.nature.com/articles/ngeo697

[...]</div>

**Details**:
- use the approach as an alternative to compute a station magnitude
- consider only those streams which are used for detection
- the time window length is equal to the length of the template waveform
- **Processing**:
    + the linear trend is removed
    + the mean is removed
    + a filter is applied
    + finally the waveform is trimmed.
- > The process is to find the maximum amplitude for each template and the corresponding detection for each station and channel. Then compute the ratio for all these pairs, and take the median.

**Comment by damb** [comment]
Both the amplitude and magnitude are going to be named `MRelative`.

**Comment by damb** [comment]
@mmesim, for clarification: if a detector configuration includes a vertical instrument component, `MRelative` is going to be computed under consideration of that vertical component, too. Though, in any case the *reference* station magnitudes are `MLhc`/`MLh`. Do you agree with this?

**Comment by mmesim** [comment]
Yes.
