### ISSUE TITLE
Allow ringbuffer size to be configurable

### ISSUE THREAD

**Issue by damb** [damb/scdetect#81]
The ringbuffer size used for waveform buffering is fixed at the time being. Allow it to be configurable.

Thanks to @luca-s for the hint.

**Comment by damb** [comment]
See also https://www.seiscomp.de/doc/apps/scautopick.html#confval-ringBufferSize.

**Comment by luca-s** [comment]
That is an useful option, however scautopick  `ringBufferSize` doesn't properly document what is useful for (one needs to look in the source code to understand that) and it doesn't explain the implication of selecting a certain value. I wish scautopick could figure it out by itself what is the optimal  `ringBufferSize` size, or, if that is not possible, provided some sensible guidelines on how to configure that buffer size
